/* ============================================================
   pulse_rate_analysis.sas
   --------------------------------------------------------
   Multiple Regression Analysis of Physiological Factors
   Predicting Resting Pulse Rate

   Workflow:
     1. Synthetic data generated via Python (generate_data.py)
     2. CSV imported into SAS Studio for all statistical analysis

   Author: Chiemela Joseph Nwosu
   ============================================================ */


/* --------------------------------------------------------
   STEP 1: Import CSV generated by Python
   -------------------------------------------------------- */
proc import datafile="/path/to/pulse_rate_data.csv"
    out=PulseRate
    dbms=csv
    replace;
    getnames=yes;
run;


/* --------------------------------------------------------
   STEP 2: Descriptive Statistics
   -------------------------------------------------------- */
proc means data=PulseRate n min max mean std;
    var Age Weight Height WBC RBC Pulse;
    title "Descriptive Statistics of Physiological Variables";
run;


/* --------------------------------------------------------
   STEP 3: Distribution Analysis of Pulse Rate
   Tests normality and visualizes distribution shape.
   -------------------------------------------------------- */
proc univariate data=PulseRate normal;
    var Pulse;
    histogram Pulse / normal;
    title "Distribution Analysis of Pulse Rate";
run;


/* --------------------------------------------------------
   STEP 4: Full Multiple Regression Model
   All 6 predictors included.
   Outputs: ANOVA table, parameter estimates,
            residual plot, observed vs. predicted plot.
   -------------------------------------------------------- */
proc reg data=PulseRate plots(only)=(residuals fitplot);
    model Pulse = Age Weight Gender Height WBC RBC;
    title "Full Model: Multiple Regression Analysis of Pulse Rate";
run;
quit;


/* --------------------------------------------------------
   STEP 5: Final Reduced Model
   Retains only the 3 significant predictors:
   Age (p=0.0132), Weight (p=0.0004), WBC (p=0.0100).

   Final equation:
     Pulse = 49.0360 - 0.2564(Age) + 0.3849(Weight) + 1.7620(WBC)

   R² = 0.8277 | Adjusted R² = 0.7702 | Root MSE = 6.2590
   -------------------------------------------------------- */
proc reg data=PulseRate;
    model Pulse = Age Weight WBC;
    output out=RegOut p=Predicted r=Residuals;
    title "Final Model: Pulse Rate Predicted by Age, Weight, and WBC";
run;
quit;


/* --------------------------------------------------------
   STEP 6: Age-Weight Interaction Analysis
   Tests whether the Age x Weight interaction term
   significantly contributes to predicting pulse rate.
   -------------------------------------------------------- */
proc glm data=PulseRate;
    model Pulse = Age Weight Age*Weight;
    title "Analysis of Age-Weight Interaction Effect on Pulse Rate";
run;
quit;


/* --------------------------------------------------------
   STEP 7: Create Age Group Categories
   Young  = Age < 35
   Middle = 35 <= Age < 50
   Older  = Age >= 50
   -------------------------------------------------------- */
data PulseAgeGroups;
    set PulseRate;
    length AgeGroup $10;
    if Age < 35 then AgeGroup = 'Young';
    else if Age < 50 then AgeGroup = 'Middle';
    else AgeGroup = 'Older';
run;


/* --------------------------------------------------------
   STEP 8: Visualization — Weight vs. Pulse by Age Group
   Scatter plot with separate regression lines per group.
   -------------------------------------------------------- */
proc sgplot data=PulseAgeGroups;
    scatter x=Weight y=Pulse / group=AgeGroup transparency=0.4
            markerattrs=(size=10);
    reg x=Weight y=Pulse / group=AgeGroup lineattrs=(thickness=2);
    xaxis label="Weight (kg)";
    yaxis label="Pulse Rate (bpm)";
    title "Weight-Pulse Relationship by Age Group";
run;
